version: '3.7'
services:
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=jasonwhitehead@cvpcorp.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - '8888:80'
  database:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  api:
    depends_on:
      - database
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - PG_HOST=database
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASSWORD=password
      - PG_DATABASE=postgres
    ports:
      - '3000:3000'
volumes:
  pgdata: